---
- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: ms_chrome_enabled|bool
  tags:
    - setup-all
    - setup-ms-chrome

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: not ms_chrome_enabled|bool
  tags:
    - setup-all
    - setup-ms-chrome
