---
# tasks file for googlechrome | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Uninstalling {{ googlechrome_app_name }}
  apt:
    name: "{{ googlechrome_app_name }}"
    state: "absent"
    force_apt_get: yes
    update_cache: yes
  become: yes

- name: Debian/Ubuntu Family | Removing repository {{ googlechrome_repo_debian }}
  apt_repository:
    repo: "{{ googlechrome_repo_debian }}"
    state: "absent"
    filename: "{{ googlechrome_repo_debian_filename }}"
    update_cache: yes
  become: yes

- name: Debian/Ubuntu Family | Remove gpg signing key for {{ googlechrome_app_name }}
  apt_key:
    url: "{{ googlechrome_gpg_key }}"
    state: absent
  become: yes
  ignore_errors: yes
